{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#단순회귀분석"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYcAAAE9CAYAAADgT65tAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8QZhcZAAAVmUlEQVR4nO3df5BlZ13n8fe3yUpsTQiQxCCku2FNYoGYaFrcwrVgQ4xR1kSNUeKt8gdoVwTK1SpZY3WkYHd73Y0oFYplU20wSnEVBaVMSiUmQUmpQejRwExISAJOt6lhTaIWVVQvIJnv/nFO7/TMc3v69qTvfU73fb+qus45z7l9+nu6Z+7nPuc5PyIzkSRps6naBUiSusdwkCQVDAdJUsFwkCQVDAdJUsFwkCQVTqtdwG44++yzc25urnYZkrSnHDhw4MnMPGfQun0RDnNzc6ysrNQuQ5L2lIhY3Wqdh5UkSQXDQZJUMBwkSQXDQZJUMBwkSYUq4RARl0TERyPi/ohYiYiXbVr3yrb9gYj4SI36JGnS1TqV9SbgrZn5pxHxve3yKyPiLOBdwJWZuRYR51aqT5ImWq3DSgmc2c4/CzjSzv8o8IeZuQaQmY9XqE2Suq/fh7k5mJpqpv3+rm6+Vs/h54A7I+JtNAH18rb9QuDfRMRfAGcAN2fme+qUKEkd1e/DwgKsrzfLq6vNMkCvtys/Ikb1JLiIuBs4b8CqReBVwEcy8w8i4oeBhcy8PCLeCcy3678auA94dWY+PGD7C8ACwMzMzKWrq1te6CdJ+8vcXBMIJ5qdhcOHh95MRBzIzPmB62o8JjQiPg+clZkZEQF8PjPPjIgbgNMz8y3t694NfCgz33+y7c3Pz6e3z5A0MaamYNB7dwQcPTr0Zk4WDrXGHI4Ar2jnLwMeaef/CPjOiDgtIqaBbwcerFCfJHXXzMzO2k9BrTGHnwZujojTgC/SHh7KzAcj4kPAJ4GjwK2ZeahSjZLUTUtLx485AExPN+27pEo4ZOZfApduse5XgV8db0WStIdsDDovLsLaWtNjWFratcFo2Ce37JakidPr7WoYnMjbZ0iSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDpO7q92FuDqammmm/X7uiiXFa7QIkaaB+HxYWYH29WV5dbZYBer16dU0Iew6Sumlx8VgwbFhfb9o1coaDpG5aW9tZu3aV4SCpm2ZmdtauXWU4SOqmpSWYnj6+bXq6adfIGQ6SuqnXg+VlmJ2FiGa6vOxg9JhUO1spIi4BbgFOB74CvD4zPxYRzwLeC8y09b0tM2+rVaekino9w6CSmj2Hm4C3ZuYlwJvbZYA3AJ/KzIuBVwK/FhFfVadESZpMNcMhgTPb+WcBRza1nxERAXwt8M80PQtJ0pjUvAju54A7I+JtNCH18rb9ncDtNGFxBvAjmXn0xG+OiAVgAWDGsxckaVeNtOcQEXdHxKEBX1cDPwP8fGaeD/w88O72274buB/4euAS4J0RceaJ287M5cycz8z5c845Z5S7IUkTZ6Q9h8y8fKt1EfEe4D+1i+8Hbm3nfxL4H5mZwKMR8ffANwIfG2WtkqRjao45HAFe0c5fBjzSzq8BrwKIiK8DLgI+O/bqJGmC1Rxz+Gng5og4Dfgi7fgB8F+B34qIg0AAv5iZT1aqUZImUrVwyMy/BC4d0H4EuGL8FUmSNniFtCSpYDhIkgqGgySpYDhIkgqGgySpYDhI2n/6fZibg6mpZtrv165ozzEcJO0v/T4sLMDqKmQ204UFeP3rDYwdqHkRnCTtvsVFWF8/vm19HW65pQkLOBYY4PMitmDPQdL+srY2uH0jGDasrzdB0jUdOSRmOEjaX3ZyC/+tgqSWrQ6JVQgIw0HS/rK0BNPTx7dFDH5t154Fs9UhsQo9HMNB0v7S68HyMszONqEwOwvXX18GxvR0EyRdslVPpkIPx3CQtP/0enD4MBw92kzf9a4yMJaXuzcYvVVPpkIPx3CQNBlODIyuBQMMPiRWqYdjOEhSVww6JFaph+N1DpLUJb1eJ3o19hwkSQXDQZJUMBwkSQXDQZJUMBwkSQXDQZJUMBwkdeZOoOoOw0HqmnG/UXfoTqDqDsNB6pIab9QduhOousNwkLqkxht1h+4Equ4wHKQuqfFG3aE7gao7DAepS2q8UXfoTqDqDsNB6pIab9QduhOousO7skpdsvGGvLjYHEqamWmCYdRv1B25E6i6w3CQusY3anWAh5UkSQXDQZJUMBwkSYUq4RARF0fEfRFxMCLuiIgzN637pYh4NCI+HRHfXaM+SZp0tXoOtwI3ZOZLgQ8CbwKIiBcDrwFeAlwJvCsinlGpRkmaWLXC4SLg3nb+LuCadv5q4H2Z+aXM/HvgUeBlFeqTpIlWKxwOAVe189cC57fzzwf+YdPrHmvbJEljNLLrHCLibuC8AasWgdcC74iINwO3A1/e+LYBr88ttr8ALADMeA8YSdpVIwuHzLx8m5dcARARFwKvbtse41gvAuAFwJEttr8MLAPMz88PDBBJ0qmpdbbSue10CrgRuKVddTvwmoh4ZkS8ELgA+FiNGiVpktUac7guIh4GHqLpGdwGkJkPAL8PfAr4EPCGzHyqUo2SNLEic+8fkZmfn8+VlZXaZUjSnhIRBzJzftA6r5CWJBUMB0lSwXCQJBUMB6m2fh/m5mBqqpn2+7UrknzYj1RVvw8LC7C+3iyvrjbL4AN/VJU9B6mmxcVjwbBhfb1pr8nezMSz5yDVtLa2s/ZxsDcj7DlIdW11X7Ca9wvram9GY2U4SDUtLcH09PFt09NNey1d7M1o7AwHqaZeD5aXYXYWIprp8nLdwzdd7M1o7AwHqbZeDw4fhqNHm2nt4/pd7M1o7AwHScfrYm9GY+fZSpJKvZ5hMOHsOUiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKlgOEiSCoaDJKmwbThExBsj4tnjKEaS1A3D9BzOAz4eEb8fEVdGRIy6KElSXduGQ2beCFwAvBv4CeCRiPjvEfFvR1ybJKmSocYcMjOB/9N+fQV4NvCBiLhphLVJkioZZszhZyPiAHAT8FfASzPzZ4BLgWtO5YdGxMURcV9EHIyIOyLizLb9uyLiQNt+ICIuO5XtS5KentOGeM3ZwA9m5urmxsw8GhH/8RR/7q3AL2TmRyLitcCbgF8GngS+LzOPRMQ3AXcCzz/FnyFJOkXDjDm8+cRg2LTuwVP8uRcB97bzd9H2QDLz7zLzSNv+AHB6RDzzFH+GNHr9PszNwdRUM+33a1ck7Ypa1zkcAq5q568Fzh/wmmuAv8vML42tKmkn+n1YWIDVVchspgsLBoT2hWjGmkew4Yi7aU6DPdEi8GngHcBzgduBn83M52763pe07Vdk5me22P4CsAAwMzNz6erqwM6NNDpzc00gnGh2Fg4fHnc10o5FxIHMnB+4blThMKyIuBB4b2a+rF1+AfBh4Ccz86+G2cb8/HyurKyMsEppgKmppsdwogg4enT89Ug7dLJwqHJYKSLObadTwI3ALe3yWcAfA780bDBI1czM7Kxd2kNqjTlcFxEPAw8BR4Db2vY3At8A/HJE3N9+nVupRunklpZgevr4tunpph0crNaeVv2w0m7wsJKq6fdhcRHW1poew9IS9HrHBqvX14+9dnoalpeb9VIHdHrMYTcYDuocB6u1B3RuzEEayl4+LLO2trN2qWMMB3XTXr+GwMFq7XGGg7ppcfH44/XQLC8u1qlnp7YbrJY6znBQN+31wzK9XjP4PDvbXPcwO+tgtPaUYW68J43fzMzgAd29dFim1zMMtGfZc1A3eVhGqspwUDd5WEaqysNK6i4Py0jV2HOQJBUMB0lSwXCQJBUMB9W1l2+RIe1jDkirnhPvXLpxiwxwIFqqzJ7DpOrCJ/a9fosMaR+z5zCJuvKJfa/fIkPax+w5TKKufGL3zqVSZxkOk6grn9i9RYbUWYbDJOrKJ3ZvkSF1luEwibr0ib3Xax6befRoMzUYpE4wHCaRn9hPXRfO8pLGwLOVJpU3tdu5rpzlJY2BPQdpWF05y0saA8NBGlZXzvKSxsBwkIbVlbO8pDEwHHSMg60n16WzvKQRMxzU2BhsXV2FzGODrQbEMZ7lpQkSmVm7hqdtfn4+V1ZWapext83NNYFwotnZ5voDSftORBzIzPlB6+w5qOFgq6RNDAc1HGyVtInhoIaDrZI2MRzUcLBV0ibePkPHeEsNSS17DpKkguEgSSpUCYeIuDgi7ouIgxFxR0ScecL6mYj4QkT8Qo36JGnS1eo53ArckJkvBT4IvOmE9W8H/nTsVUmSgHrhcBFwbzt/F3DNxoqI+H7gs8ADFeqSJFEvHA4BV7Xz1wLnA0TE1wC/CLx1uw1ExEJErETEyhNPPDGyQiVpEo0sHCLi7og4NODrauC1wBsi4gBwBvDl9tveCrw9M7+w3fYzczkz5zNz/pxzzhnVbkjSRBrZdQ6Zefk2L7kCICIuBF7dtn078EMRcRNwFnA0Ir6Yme8cVZ2SpFKVi+Ai4tzMfDwipoAbgVsAMvM7N73mLcAXDAZJGr9aYw7XRcTDwEPAEeC2SnVIkgao0nPIzJuBm7d5zVvGU40k6UReIS1JKhgOkqSC4SBJKhgOkqSC4SBJKhgOkqSC4SBJKhgOkqSC4SBJKhgOkqSC4SBJKhgOkqSC4SBJKhgOkqSC4SBJKhgOo9Lvw9wcTE01036/dkWSNLQqD/vZ9/p9WFiA9fVmeXW1WQbo9erVJUlDsucwCouLx4Jhw/p60y5Je4DhMApraztrl6SOMRxGYWZmZ+2S1DGGwygsLcH09PFt09NNuyTtAYbDKPR6sLwMs7MQ0UyXlx2MlrRneLbSqPR6hoGkPcuegySpYDhIkgqGgySpYDhIkgqGgySpYDhIkgqGgySpYDhIkgqGgySpYDhIkgqGgySpUCUcIuLiiLgvIg5GxB0Rceamdd/crnugXX96jRolaZLV6jncCtyQmS8FPgi8CSAiTgPeC1yfmS8BXgn8a6UaJWli1QqHi4B72/m7gGva+SuAT2bmJwAy858y86kK9UnSRKsVDoeAq9r5a4Hz2/kLgYyIOyPibyPiP1epTpIm3Mie5xARdwPnDVi1CLwWeEdEvBm4Hfjypnr+PfBtwDpwT0QcyMx7Bmx/AVgAmPHxm5K0q0YWDpl5+TYvuQIgIi4EXt22PQZ8JDOfbNf9CfCtQBEOmbkMLAPMz8/nLpUtSaLe2UrnttMp4EbglnbVncA3R8R0Ozj9CuBTNWqUpElWa8zhuoh4GHgIOALcBpCZ/wL8OvBx4H7gbzPzjyvVKEkTq8ozpDPzZuDmLda9l+Z0VklSJV4hLUkqGA6SpILhIEkqGA6SpILhIEkqGA6SpILh0CX9PszNwdRUM+33a1ckaUJVuc5BA/T7sLAA6+vN8upqswzQ69WrS9JEsufQFYuLx4Jhw/p60y5JY2Y4dMXq6s7aJWmEDIeueMYzdtYuSSNkOHTFU1s88G6rdkkaIcOhK2Znd9YuSSNkOHTF0hJMTx/fNj3dtEvSmBkOXdHrwfJy01OIaKbLy57GKqkKr3Pokl7PMJDUCfYcJEkFw0GSVDAcJEkFw0GSVDAcJEkFw0GSVJjscPD5CZI00ORe5+DzEyRpS5Pbc/D5CZK0pckNh7W1nbVL0gSZ3HCYmdlZuyRNkMkNB++CKklbmtxw8C6okrSlyT1bCbwLqiRtYXJ7DpKkLRkOkqSC4SBJKhgOkqSC4SBJKhgOkqSC4SBJKhgOkqRCZGbtGp62iHgCWK1dxy44G3iydhG7bL/tk/vTffttn0a5P7OZec6gFfsiHPaLiFjJzPnadeym/bZP7k/37bd9qrU/HlaSJBUMB0lSwXDoluXaBYzAftsn96f79ts+VdkfxxwkSQV7DpKkguFQUURcGxEPRMTRiNjybISIOBwRByPi/ohYGWeNO7WDfboyIj4dEY9GxA3jrHEnIuI5EXFXRDzSTp+9xeueav8+90fE7eOuczvb/b4j4pkR8Xvt+r+JiLnxVzm8IfbnJyLiiU1/k5+qUeewIuI3I+LxiDi0xfqIiHe0+/vJiPjWUddkONR1CPhB4N4hXvsfMvOSPXCK3rb7FBHPAP4X8D3Ai4HrIuLF4ylvx24A7snMC4B72uVB/m/797kkM68aX3nbG/L3/TrgXzLzG4C3A/9zvFUObwf/fn5v09/k1rEWuXO/BVx5kvXfA1zQfi0A/3vUBRkOFWXmg5n56dp17KYh9+llwKOZ+dnM/DLwPuDq0Vd3Sq4Gfrud/23g+yvWcqqG+X1v3s8PAK+KiBhjjTuxl/79DCUz7wX++SQvuRp4TzY+CpwVEc8bZU2Gw96QwJ9FxIGIWKhdzC54PvAPm5Yfa9u66Osy83MA7fTcLV53ekSsRMRHI6JrATLM7/v/vyYzvwJ8HnjuWKrbuWH//VzTHoL5QEScP57SRmbs/2cm+xnSYxARdwPnDVi1mJl/NORmviMzj0TEucBdEfFQ+0mjil3Yp0GfSKudNney/dnBZmbav9GLgA9HxMHM/MzuVPi0DfP77tTfZBvD1HoH8LuZ+aWIuJ6mV3TZyCsbnbH/fQyHEcvMy3dhG0fa6eMR8UGabnW1cNiFfXoM2PxJ7gXAkae5zVN2sv2JiH+MiOdl5ufabvzjW2xj42/02Yj4C+BbgK6EwzC/743XPBYRpwHP4uSHOWradn8y8582Lf4GHR5DGdLY/894WKnjIuJrIuKMjXngCppB373s48AFEfHCiPgq4DVA587wad0O/Hg7/+NA0TOKiGdHxDPb+bOB7wA+NbYKtzfM73vzfv4Q8OHs7kVQ2+7PCcfjrwIeHGN9o3A78GPtWUv/Dvj8xuHOkclMvyp9AT9A84ngS8A/Ane27V8P/Ek7/yLgE+3XAzSHbqrX/nT2qV3+XuBhmk/Xnd0nmuPu9wCPtNPntO3zwK3t/MuBg+3f6CDwutp1D9iP4vcN/Bfgqnb+dOD9wKPAx4AX1a75ae7Pr7T/Xz4B/DnwjbVr3mZ/fhf4HPCv7f+f1wHXA9e364PmDK3PtP/G5kddk1dIS5IKHlaSJBUMB0lSwXCQJBUMB0lSwXCQJBUMB0lSwXCQJBUMB2kEIuLb2pu+nd5e5f5ARHxT7bqkYXkRnDQiEfHfaK48/mrgscz8lcolSUMzHKQRae/783Hgi8DLM/OpyiVJQ/OwkjQ6zwG+FjiDpgch7Rn2HKQRaZ8l/T7ghcDzMvONlUuShubzHKQRiIgfA76Smb/TPvP4ryPissz8cO3apGHYc5AkFRxzkCQVDAdJUsFwkCQVDAdJUsFwkCQVDAdJUsFwkCQVDAdJUuH/AbkmGf5xRWz/AAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x360 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import numpy as np\n",
    "\n",
    "dataSize = 20\n",
    "xData = []\n",
    "yData = []\n",
    "\n",
    "# 자료의 형태 설정\n",
    "wi = 3.5\n",
    "bi = - 90\n",
    "\n",
    "# 랜덤 데이터 생성\n",
    "for i in range(dataSize):\n",
    "    xi = np.random.normal(0.0, 1.0)\n",
    "    yi = wi * xi + bi + np.random.normal(0.0, 1.0)\n",
    "    xData.append([xi])\n",
    "    yData.append([yi])\n",
    "    \n",
    "# 플롯 작성\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline\n",
    "\n",
    "fig = plt.figure(figsize = (6, 5))\n",
    "plt.plot(xData, yData, 'ro')\n",
    "plt.xlabel('x')\n",
    "plt.ylabel('y')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3326, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-4-9cbb6f0e8980>\", line 4, in <module>\n",
      "    w = tf.Variable(tf.random_uniform([1], -1.0, 1.0))\n",
      "AttributeError: module 'tensorflow' has no attribute 'Variable'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2040, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\imp.py\", line 242, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\imp.py\", line 342, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 42, in <module>\n",
      "    from . _api.v2 import audio\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\_api\\v2\\audio\\__init__.py\", line 10, in <module>\n",
      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\ops\\gen_audio_ops.py\", line 9, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3326, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-4-9cbb6f0e8980>\", line 4, in <module>\n",
      "    w = tf.Variable(tf.random_uniform([1], -1.0, 1.0))\n",
      "AttributeError: module 'tensorflow' has no attribute 'Variable'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2040, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\imp.py\", line 242, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\imp.py\", line 342, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.\n",
      "\n",
      "\n",
      "Failed to load the native TensorFlow runtime.\n",
      "\n",
      "See https://www.tensorflow.org/install/errors\n",
      "\n",
      "for some common reasons and solutions.  Include the entire stack trace\n",
      "above this error message when asking for help.\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "module 'tensorflow' has no attribute 'Variable'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m"
     ]
    }
   ],
   "source": [
    "# 머신러닝 시작\n",
    "import tensorflow as tf\n",
    "\n",
    "w = tf.Variable(tf.random_uniform([1], -1.0, 1.0))\n",
    "b = tf.Variable(tf.zeros([1]))\n",
    "y = w * xData + b\n",
    "\n",
    "# mse를 최소화하는 비용함수\n",
    "loss = tf.reduce_mean(tf.square(y - yData))\n",
    "\n",
    "optimizer = tf.train.GradientDescentOptimizer(0.5)\n",
    "train = optimizer.minimize(loss)\n",
    "\n",
    "init = tf.global_variables_initializer()\n",
    "\n",
    "sess = tf.Session()\n",
    "sess.run(init)\n",
    "\n",
    "# 머신러닝 반복에 따른 회귀식 변화\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline\n",
    "\n",
    "fig = plt.figure(figsize = (15, 40))\n",
    "\n",
    "for step in range(10):\n",
    "    sess.run(train)\n",
    "    cf = sess.run(loss)\n",
    "    wt = sess.run(w)\n",
    "    bt = sess.run(b)\n",
    "    print(\"loss:\",loss, \"cf:\",cf, \"wt:\",wt, \"bt:\", bt)\n",
    "    \n",
    "    subfig = fig.add_subplot(10, 3, step + 1)\n",
    "    plt.plot(xData, yData, 'ro')\n",
    "    plt.plot(xData, wt * xData + bt)\n",
    "    plt.tight_layout()\n",
    "    subfig.set_title('Step ' \n",
    "                     + str(step + 1) + '] loss = ' + str(round(cf, 2)) \n",
    "                     + ', y = ' + str(round(wt[0], 2)) + 'x + ' + str(round(bt[0], 2)))\n",
    "    subfig.set_xlabel('x')\n",
    "    subfig.set_ylabel('y')\n",
    "    \n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3326, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-4-448d26e55a72>\", line 1, in <module>\n",
      "    b = tf.Variable(tf.zeros([1]))\n",
      "AttributeError: module 'tensorflow' has no attribute 'Variable'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2040, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\imp.py\", line 242, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\imp.py\", line 342, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 42, in <module>\n",
      "    from . _api.v2 import audio\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\_api\\v2\\audio\\__init__.py\", line 10, in <module>\n",
      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\ops\\gen_audio_ops.py\", line 9, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3326, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-4-448d26e55a72>\", line 1, in <module>\n",
      "    b = tf.Variable(tf.zeros([1]))\n",
      "AttributeError: module 'tensorflow' has no attribute 'Variable'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2040, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\imp.py\", line 242, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"C:\\Users\\04432\\AppData\\Local\\Continuum\\anaconda3\\lib\\imp.py\", line 342, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.\n",
      "\n",
      "\n",
      "Failed to load the native TensorFlow runtime.\n",
      "\n",
      "See https://www.tensorflow.org/install/errors\n",
      "\n",
      "for some common reasons and solutions.  Include the entire stack trace\n",
      "above this error message when asking for help.\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "module 'tensorflow' has no attribute 'Variable'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m"
     ]
    }
   ],
   "source": [
    "\n",
    "b = tf.Variable(tf.zeros([1]))\n",
    "y = w * xData + b\n",
    "print(b)\n",
    "print(y)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
